signum-explorer/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from scan.views.accounts import AccountsListView, AddressDetailView
from scan.views.assets import (
    AssetDetailView,
    AssetMintingDetailView,
    AssetDistributionDetailView,
    AssetHoldersListView,
    AssetListView,
    AssetTradesListView,
    AssetTransfersListView,
    
)
from scan.views.ats import AtDetailView, AtListView
from scan.views.blocks import BlockDetailView, BlockListView
from scan.views.index import index
from scan.views.marketplace import (
    MarketPlaceDetailView,
    MarketPlaceListView,
    MarketPlacePurchasesListView,
)
from scan.views.peers import (
    PeerMonitorDetailView,
    PeerMonitorListView,
    peers_charts_view,
)
from scan.views.pending_transactions import pending_transactions
from scan.views.search import search_view
from scan.views.transactions import TxDetailView, TxListView, tx_export_csv
from scan.views.cashbacks import CBListView
from scan.views.distribution import DistributionListView

urlpatterns = [
    path("", index, name="index"),
    path("distribution/", DistributionListView.as_view(), name="distribution"),
    path("cbs/", CBListView.as_view(), name="cbs"),
    path("blocks/", BlockListView.as_view(), name="blocks"),
    path("block/<str:height>", BlockDetailView.as_view(), name="block-detail"),
    path("txsPending/", pending_transactions, name="txs-pending"),
    path("txs/", TxListView.as_view(), name="txs"),
    path("tx/<str:id>", TxDetailView.as_view(), name="tx-detail"),
    path("accounts/", AccountsListView.as_view(), name="accounts"),
    path("address/<str:id>", AddressDetailView.as_view(), name="address-detail"),
    path("csv/<str:id>", tx_export_csv, name="account-csv"),
    path("asset/trades", AssetTradesListView.as_view(), name="asset-trades"),
    path("asset/transfers", AssetTransfersListView.as_view(), name="asset-transfers"),
    path("asset/holders", AssetHoldersListView.as_view(), name="asset-holders"),
    path("asset/mintings", AssetMintingDetailView.as_view(), name="asset-mintings"),
    path("asset/distributions", AssetDistributionDetailView.as_view(), name="asset-distributions"),
    path("assets/", AssetListView.as_view(), name="assets"),
    path("asset/<str:id>", AssetDetailView.as_view(), name="asset-detail"),
    path("mps/purchases", MarketPlacePurchasesListView.as_view(), name="mps-purchases"),
    path("mps/", MarketPlaceListView.as_view(), name="mps"),
    path("mp/<str:id>", MarketPlaceDetailView.as_view(), name="mp-detail"),
    path("ats/", AtListView.as_view(), name="ats"),
    path("at/<str:id>", AtDetailView.as_view(), name="at-detail"),
    path("search/", search_view, name="search"),
    path("peers/", PeerMonitorListView.as_view(), name="peers"),
    path("peers-charts/", peers_charts_view, name="peers-charts"),
    path("peer/<str:address>", PeerMonitorDetailView.as_view(), name="peer-detail"),
    # path("admin/", admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns
    urlpatterns = [path('django_query_profiler/', include('django_query_profiler.client.urls'))] + urlpatterns

signum-explorer/java_wallet/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = True` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
import os
from django.db import models
from requests import delete
from .fields import PositiveBigIntegerField, TimestampField



class Account(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField()
    creation_height = models.IntegerField()
    public_key = models.CharField(max_length=32, blank=True, null=True)
    key_height = models.IntegerField(blank=True, null=True)
    # liningupdate
    name = models.CharField(max_length=100, blank=True, null=True)
    # name = PositiveBigIntegerField()
    description = models.TextField(blank=True, null=True)
    height = models.IntegerField()
    latest = models.IntegerField()
    class Meta:
        managed = True
        db_table = 'account'
        unique_together = (('id', 'height'),)

class AccountBalance(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField()
    balance = PositiveBigIntegerField()
    unconfirmed_balance = PositiveBigIntegerField()
    forged_balance = PositiveBigIntegerField()
    height = models.IntegerField()
    latest = models.IntegerField()
    class Meta:
        managed = True
        # liningupdate
        # db_table = 'account_balance'
        db_table = 'account'
        unique_together = (('id', 'height'),)

class AccountAsset(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    account_id = PositiveBigIntegerField()
    asset_id = PositiveBigIntegerField()
    quantity = PositiveBigIntegerField()
    unconfirmed_quantity = PositiveBigIntegerField()
    height = models.IntegerField()
    latest = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'account_asset'
        unique_together = (('account_id', 'asset_id', 'height'),)


class Alias(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField()
    account_id = PositiveBigIntegerField()
    alias_name = models.CharField(max_length=100)
    alias_name_lower = models.CharField(max_length=100)
    alias_uri = models.TextField()
    timestamp = TimestampField()
    height = models.IntegerField()
    latest = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'alias'
        unique_together = (('id', 'height'),)


class AliasOffer(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField()
    price = PositiveBigIntegerField()
    buyer_id = PositiveBigIntegerField(blank=True, null=True)
    height = models.IntegerField()
    latest = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'alias_offer'
        unique_together = (('id', 'height'),)


class AskOrder(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField()
    account_id = PositiveBigIntegerField()
    asset_id = PositiveBigIntegerField()
    price = PositiveBigIntegerField()
    quantity = PositiveBigIntegerField()
    creation_height = models.IntegerField()
    height = models.IntegerField()
    latest = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'ask_order'
        unique_together = (('id', 'height'),)


class Asset(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField(unique=True)
    account_id = PositiveBigIntegerField()
    name = models.CharField(max_length=10)
    description = models.TextField(blank=True, null=True)
    quantity = PositiveBigIntegerField()
    decimals = models.IntegerField()
    height = models.IntegerField()
    mintable = models.BooleanField()

    class Meta:
        managed = True
        db_table = 'asset'


class AssetTransfer(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField(unique=True)
    asset_id = PositiveBigIntegerField()
    sender_id = PositiveBigIntegerField()
    recipient_id = PositiveBigIntegerField()
    quantity = PositiveBigIntegerField()
    timestamp = TimestampField()
    height = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'asset_transfer'


class At(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField()
    creator_id = PositiveBigIntegerField()
    name = models.CharField(max_length=30, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    version = models.SmallIntegerField()
    csize = models.IntegerField()
    dsize = models.IntegerField()
    c_user_stack_bytes = models.IntegerField()
    c_call_stack_bytes = models.IntegerField()
    creation_height = models.IntegerField()
    ap_code = models.BinaryField()
    height = models.IntegerField()
    latest = models.IntegerField()
    ap_code_hash_id = PositiveBigIntegerField()

    class Meta:
        managed = True
        db_table = 'at'
        unique_together = (('id', 'height'),)


class AtState(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    at_id = PositiveBigIntegerField()
    state = models.BinaryField()
    prev_height = models.IntegerField()
    next_height = models.IntegerField()
    sleep_between = models.IntegerField()
    prev_balance = PositiveBigIntegerField()
    freeze_when_same_balance = models.IntegerField()
    min_activate_amount = PositiveBigIntegerField()
    height = models.IntegerField()
    latest = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'at_state'
        unique_together = (('at_id', 'height'),)


class BidOrder(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField()
    account_id = PositiveBigIntegerField()
    asset_id = PositiveBigIntegerField()
    price = PositiveBigIntegerField()
    quantity = PositiveBigIntegerField()
    creation_height = models.IntegerField()
    height = models.IntegerField()
    latest = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'bid_order'
        unique_together = (('id', 'height'),)


class Block(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField(unique=True)
    version = models.IntegerField()
    timestamp = TimestampField(unique=True)
    previous_block = models.ForeignKey('self', models.DO_NOTHING, blank=True, null=True, related_name='previous_block_r', to_field='id')
    total_amount = PositiveBigIntegerField()
    total_fee = PositiveBigIntegerField()
    payload_length = models.IntegerField()
    generator_public_key = models.CharField(max_length=32)
    previous_block_hash = models.CharField(max_length=32, blank=True, null=True)
    cumulative_difficulty = models.TextField()
    base_target = PositiveBigIntegerField()
    next_block = models.ForeignKey('self', models.DO_NOTHING, blank=True, null=True, related_name='next_block_r', to_field='id')
    height = models.IntegerField(unique=True)
    generation_signature = models.BinaryField(max_length=64)
    block_signature = models.CharField(max_length=64)
    payload_hash = models.CharField(max_length=32)
    generator_id = PositiveBigIntegerField()
    nonce = PositiveBigIntegerField()
    ats = models.TextField(blank=True, null=True)
    version = os.environ.get('BRS_P2P_VERSION')
    # liningupdate
    total_fee_cash_back = 1
    total_fee_burnt = 1
    # total_fee_cash_back = PositiveBigIntegerField()
    # total_fee_burnt = PositiveBigIntegerField()

    class Meta:
        managed = True
        db_table = 'block'


class Escrow(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField()
    sender_id = PositiveBigIntegerField()
    recipient_id = PositiveBigIntegerField()
    amount = PositiveBigIntegerField()
    required_signers = models.IntegerField(blank=True, null=True)
    deadline = models.IntegerField()
    deadline_action = models.IntegerField()
    height = models.IntegerField()
    latest = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'escrow'
        unique_together = (('id', 'height'),)


class EscrowDecision(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    escrow_id = PositiveBigIntegerField()
    account_id = PositiveBigIntegerField()
    decision = models.IntegerField()
    height = models.IntegerField()
    latest = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'escrow_decision'
        unique_together = (('escrow_id', 'account_id', 'height'),)


class Goods(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField()
    seller_id = PositiveBigIntegerField()
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    tags = models.CharField(max_length=100, blank=True, null=True)
    timestamp = TimestampField()
    quantity = models.IntegerField()
    price = PositiveBigIntegerField()
    delisted = models.IntegerField()
    height = models.IntegerField()
    latest = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'goods'
        unique_together = (('id', 'height'),)


class Peer(models.Model):
    address = models.CharField(primary_key=True, max_length=100)

    class Meta:
        managed = True
        db_table = 'peer'


class Purchase(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField()
    buyer_id = PositiveBigIntegerField()
    goods_id = PositiveBigIntegerField()

signum-explorer/scan/views/ats.py
import gzip
from django.views.generic import ListView

from java_wallet.models import At
from scan.caching_paginator import CachingPaginator
from scan.helpers.queries import get_account_name, get_ap_code, get_at_state
from scan.views.base import IntSlugDetailView


def fill_at_data(obj):
    obj.creator_name = get_account_name(obj.creator_id)
    if not obj.ap_code and obj.ap_code_hash_id:
        obj.ap_code = get_ap_code(obj.ap_code_hash_id)

    state, obj.activation = get_at_state(obj.id)
    # skip the internal state, balances, etc.
    obj.state = gzip.decompress(state)[106:]


class AtListView(ListView):
    model = At
    queryset = At.objects.using("java_wallet").filter(latest=True).all()
    template_name = "ats/list.html"
    context_object_name = "ats"
    paginator_class = CachingPaginator
    paginate_by = 25
    ordering = "-height"

    def get_queryset(self):
        qs = self.queryset
        if 'a' in self.request.GET:
            qs = qs.filter(creator_id=self.request.GET['a'])

        return qs.order_by(self.ordering)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        obj = context[self.context_object_name]
        for t in obj:
            fill_at_data(t)

        return context


class AtDetailView(IntSlugDetailView):
    model = At
    queryset = At.objects.using("java_wallet").filter(latest=True).all()
    template_name = "ats/detail.html"
    context_object_name = "at"
    slug_field = "id"
    slug_url_kwarg = "id"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        obj = context[self.context_object_name]
        fill_at_data(obj)

        return context

signum-explorer/scan/views/base.py
from django.http import Http404
from django.utils.translation import gettext as _
from django.views.generic import DetailView


class IntSlugDetailView(DetailView):
    def get_object(self, queryset=None):
        slug = self.kwargs.get(self.slug_url_kwarg)
        if not slug.isdigit():
            raise Http404(
                _("No %(verbose_name)s found matching the query")
                % {"verbose_name": self.queryset.model._meta.verbose_name}
            )

        return super().get_object(queryset)

signum-explorer/scan/views/blocks.py
from django.views.generic import ListView

from java_wallet.models import Block
from scan.caching_data.last_height import CachingLastHeight
from scan.caching_paginator import CachingPaginator
from scan.helpers.queries import (
    get_account_name,
    get_pool_id_for_block,
    get_txs_count_in_block,
)
from scan.views.base import IntSlugDetailView
from scan.views.filters.blocks import BlockFilter


def fill_data_block(obj):
    obj.txs_cnt = get_txs_count_in_block(obj.id)
    obj.generator_name = get_account_name(obj.generator_id)

    pool_id = get_pool_id_for_block(obj)
    if pool_id:
        obj.pool_id = pool_id
        obj.pool_name = get_account_name(pool_id)


class BlockListView(ListView):
    model = Block
    queryset = Block.objects.using("java_wallet").all()
    template_name = "blocks/list.html"
    context_object_name = "blocks"
    paginator_class = CachingPaginator
    paginate_by = 25
    ordering = "-height"

    def get_queryset(self):
        return BlockFilter(self.request.GET, queryset=super().get_queryset()).qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["last_height"] = CachingLastHeight().cached_data
        obj = context[self.context_object_name]
        for b in obj:
            fill_data_block(b)

        return context


class BlockDetailView(IntSlugDetailView):
    model = Block
    queryset = Block.objects.using("java_wallet").all()
    template_name = "blocks/detail.html"
    context_object_name = "blk"
    slug_field = "height"
    slug_url_kwarg = "height"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        obj = context[self.context_object_name]
        fill_data_block(obj)
        return context

signum-explorer/scan/views/pending_transactions.py
from django.shortcuts import render

from scan.helpers.queries import get_unconfirmed_transactions

def pending_transactions(request):
    context = {"txs_pending": get_unconfirmed_transactions()}
    return render(request, "txs_pending/list.html", context)

signum-explorer/scan/templates/peers/charts.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %} - Nodes Distribution around the Globe{% endblock %}

{% block scripts %}

  <script src="https://code.highcharts.com/maps/highmaps.js"></script>
  <script src="https://code.highcharts.com/maps/modules/data.js"></script>
  <script src="https://code.highcharts.com/maps/modules/exporting.js"></script>
  <script src="https://code.highcharts.com/modules/export-data.js"></script>
  <script src="https://code.highcharts.com/mapdata/custom/world.js"></script>
  <script src="https://code.highcharts.com/highcharts.js"></script>
  <script src="https://code.highcharts.com/highcharts-more.js"></script>
  <script src="https://code.highcharts.com/modules/solid-gauge.js"></script>

  <script type="text/javascript">

var data = [
  ['Country', 'Peers'],
{% for country in countries %}['{{ country.country_code }}', {{ country.cnt }}],{% endfor %}
];

var objs = data.map(function(x) {
  return {
    'code': x[0],
    'z': x[1]
  };
});

var chart = Highcharts.mapChart('geochart', {
  chart: {
    map: 'custom/world'
  },

          title: {
            text: '',
            align: 'left'
        },

      legend: {
        enabled: false
    },

       credits: {
        enabled: false
    },

  mapNavigation: {
    enabled: true,
    buttonOptions: {
      verticalAlign: 'bottom'
    }
  },

  series: [{
    color: '#E0E0E0',
    enableMouseTracking: false,
    showInLegend: false
  }, {
    name: 'Nodes',
    type: 'mapbubble',
    joinBy: ['iso-a2', 'code'],
    data: objs,
    minSize: 4,
    maxSize: '12%',
  }]

});

  </script>

  <script type="text/javascript">

 Highcharts.chart('piechart-versions', {
    chart: {
        plotBackgroundColor: null,
        plotBorderWidth: null,
        plotShadow: false,
        type: 'pie',
        marginLeft: 0

    },

        legend: {
        align: 'left',
        verticalAlign: 'top',
        layout: 'vertical',
        x: 0,
        y: 40
    },

    title: {
        text: 'Versions (Online)',
        align: 'left'
    },

    credits: {
        enabled: false
    },

    exporting: {
        enabled: false
    },

    tooltip: {
        pointFormat: '<b>{point.y} ({point.percentage:.1f}%)</b>'
    },

    plotOptions: {
        pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            dataLabels: {
                enabled: false
            },
            showInLegend: true
        }
    },

    series: [{
        name: 'Version',
        colorByPoint: true,
        animation: {
	 enabled: true,
	 duration: 300,
	 easing: 'linear'
        },
        data: [{% for version in versions %}['{{ version.version }}', {{ version.cnt }}],{% endfor %}]
    }]
});

  </script>


  <script type="text/javascript">

Highcharts.chart('piechart-states', {
    chart: {
        plotBackgroundColor: null,
        plotBorderWidth: null,
        plotShadow: false,
        type: 'pie',
        marginLeft: 0
    },

        legend: {
        align: 'left',
        verticalAlign: 'top',
        layout: 'vertical',
        x: 0,
        y: 40
    },

    title: {
        text: 'All known nodes (last 5 days)',
        align: 'left'
    },

    credits: {
        enabled: false
    },

    exporting: {
        enabled: false
    },

    tooltip: {
        pointFormat: '<b>{point.y} ({point.percentage:.1f}%)</b>'
    },

    plotOptions: {
        pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            dataLabels: {
                enabled: false
            },
            showInLegend: true
        }
    },

    series: [{
        name: 'State',
        colorByPoint: true,
        animation: {
	 enabled: true,
	 duration: 300,
	 easing: 'linear'
        },
        data: [{% for state in states %}['{{ state.state }}', {{ state.cnt }}],{% endfor %}]
    }]
});
  </script>

    <script type="text/javascript">
var gaugeOptions = {
    chart: {
        type: 'solidgauge'
    },

    title: {
        text: '<div style="text-align:center">' +
                '<span>Online Now</span><br/>' +
                '<span style="font-size:12px;opacity:0.4">checked {{ last_check.modified_at|naturaltime }}</span>' +
                '</div>',
        align: 'left'
    },

    pane: {
        center: ['50%', '75%'],
        size: '140%',
        startAngle: -90,
        endAngle: 90,
        background: {
            backgroundColor:
                Highcharts.defaultOptions.legend.backgroundColor || '#EEE',
            innerRadius: '60%',
            outerRadius: '100%',
            shape: 'arc'
        }
    },

    exporting: {
        enabled: false
    },

    tooltip: {
        enabled: false
    },

    // the value axis
    yAxis: {
        lineWidth: 0,
        tickWidth: 0,
        minorTickInterval: null,
        tickAmount: 2,
        title: {
            y: -70
        },
        labels: {
            y: 16
        }
    },

    plotOptions: {
        solidgauge: {
            dataLabels: {
                y: 5,
                borderWidth: 0,
                useHTML: true
            }
        }
    }
};

var chartSpeed = Highcharts.chart('container-nodes', Highcharts.merge(gaugeOptions, {
    yAxis: {
        min: 0,
        max: 400,
    },

    credits: {
        enabled: false
    },

    series: [{
        name: 'Nodes',
        data: [{{ online_now }}],
        dataLabels: {
            format:
                '<div style="text-align:center">' +
                '<span style="font-size:25px">{y}</span><br/>' +
                '<span style="font-size:12px;opacity:0.4"> Nodes</span>' +
                '</div>'
        },
        tooltip: {
            valueSuffix: 'nodes'
        }
    }]

}));

  </script>

{% endblock %}

{% block content %}

  <h5 class="p-2">Nodes Distribution</h5>

  <div class="card-deck mb-3">
    <div class="card mb-4 shadow-sm">
      <div class="card-body">
          <div id="geochart" style="height: 500px; max-width: 1300px; margin: 0 auto"></div>
        <div class="row mx-gutters-md-1 pt-4">
          <div class="col-md-6 col-lg-4">
            <div class="media align-items-center">
             <div id="piechart-versions" style="height: 200px; width: 400px; min-width: 357px; margin: 0 auto"></div>
          </div>
          </div>
          <div class="col-md-6 col-lg-4">
            <div class="media align-items-center">
             <div id="container-nodes" style="height: 200px; width: 400px; min-width: 357px; margin: 0 auto"></div>
            </div>
           </div>
          <div class="col-md-6 col-lg-4 mx-auto">
            <div class="media align-items-center">
             <div id="piechart-states" style="height: 200px; width: 400px; min-width: 357px; margin: 0 auto"></div>
           </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

signum-explorer/scan/templates/peers/detail.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %} - Peer {{ peer.announced_address }}{% endblock %}

{% block content %}

  <h5 class="p-2">Peer {{ peer.announced_address }}</h5>

  <div class="card-deck mb-3">
    <div class="card mb-4 shadow-sm">
      <div class="card-body">

        <div class="table-responsive">
          <table class="table small table-sm">
            <tbody>
            <tr>
              <th style="width: 160px;">State</th>
              <td>{{ peer.get_state_display }}</td>
            </tr>
            <tr>
              <th>Height</th>
              <td>{{ peer.height }}</td>
            </tr>
            <tr>
              <th>Availability</th>
              <td>{{ peer.availability|floatformat:2 }}%</td>
            </tr>
            <tr>
              <th>Version</th>
              <td>{{ peer.version }}</td>
            </tr>
            <tr>
              <th>Country</th>
              <td>{{ peer.country_code }}</td>
            </tr>
            <tr>
              <th>Application</th>
              <td>{{ peer.application }}</td>
            </tr>
            <tr>
              <th>Platform</th>
              <td>{{ peer.platform }} <a class="btn btn-sm btn-icon btn-soft-secondary rounded-circle my-n2 px-2" href="/search/?q={{ peer.platform }}&submit=Search"><i class="fas fa-search" data-toggle="modal" title="" data-original-title="Search"></i></a></td>
            </tr>
              {% if peer.reward_state == 'Queued' or peer.reward_state == 'Paid' or peer.reward_state == 'Duplicate' %}
            <tr>
              <th>Reward Status</th>
              <td>{{ peer.reward_state }}</td>
            </tr>
            <tr>
              <th>Reward Sent</th>
              <td>{{ peer.reward_time|naturaltime }}</td>
            </tr>
              {% endif %}
            <tr>
              <th>Found</th>
              <td>{{ peer.created_at|naturaltime }}</td>
            </tr>
            <tr>
              <th>Last Online</th>
              <td>{{ peer.last_online_at|naturaltime }}</td>
            </tr>
            <tr>
              <th>Checked</th>
              <td>{{ peer.modified_at|naturaltime }}</td>
            </tr>
            </tbody>
          </table>
        </div>

      </div>
    </div>
  </div>

{% endblock %}

signum-explorer/scan/templates/peers/list.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %} - Nodes List{% endblock %}

{% block content %}

  <h5 class="p-2">Featured Nodes</h5>

  <div class="card-deck mb-3">
    <div class="card mb-4 shadow-sm">
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-hover small table-sm">
            <thead>
            <tr>
              <th scope="col">Address</th>
              <th scope="col">State</th>
              <th scope="col">Web-Wallet</th>
              <th scope="col">Height</th>
              <th scope="col">Version</th>
              <th scope="col">Country</th>
            </tr>
            </thead>
            <tbody>
            {% for peer in featured_peers %}
              <tr>
                <td><a href="{% url 'peer-detail' peer.announced_address %}">{{ peer.announced_address }}</a></td>
                <td>{{ peer.get_state_display }}</td>
                <td><a href="https://{{ peer.announced_address }}" target="_blank">https://{{ peer.announced_address }}</a></td>
                <td>{{ peer.height }}</td>
                <td>{{ peer.version }}</td>
                <td>{{ peer.country_code }}</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>


  <h5 class="p-2">Node List</h5>

  <div class="card-deck mb-3">
    <div class="card mb-4 shadow-sm">
      <div class="card-body">
        <div class="d-flex flex-column flex-md-row align-items-center">
          <small class="my-0 mr-md-auto text-muted">
              A total of {{ paginator.count|intcomma }} nodes found
          </small>
          {% include "paginator.html" %}
        </div>

        <div class="table-responsive">
          <table class="table table-hover small table-sm">
            <thead>
            <tr>
              <th scope="col">Address</th>
              <th scope="col">State</th>
              <th scope="col">Availability</th>
              <th scope="col">Height</th>
              <th scope="col">Version</th>
              <th scope="col">Country</th>
            </tr>
            </thead>
            <tbody>
            {% for peer in peers %}
              <tr>
                <td><a href="{% url 'peer-detail' peer.announced_address %}">{{ peer.announced_address }}</a></td>
                <td>{{ peer.get_state_display }}</td>
                <td>{{ peer.availability|floatformat:2 }}%</td>
                <td>{{ peer.height }}</td>
                <td>{{ peer.version }}</td>
                <td>{{ peer.country_code }}</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>

        {% include "paginator.html" %}

      </div>
    </div>
  </div>

{% endblock %}